try_django/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
]

try_django/mysite/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('articles/', views.ArticleView.as_view(), name = 'all_article'),
    path('articles/<int:year>/', views.year_archive, name = 'year'),
    #path('articles/<int:year>/', views.YearView.as_view(), name = 'year_archive'),
    path('articles/<int:year>/<int:month>/', views.month_archive , name = 'month' ),
    path('articles/<int:year>/<int:month>/<int:pk>/', views.DetailView.as_view(), name = 'detail'),
] 

"""urlpatterns =[
    path('articles/', views.article_archive),
    path('articles/<int:year>/', views.YearView.as_view()), name = 'year_archive'),
    path('articles/<int:year>/<int:month>/', views.MonthView.as_view(), name = 'month_archive' ),
    path('articles/<int:year>/<int:month>/<int:pk>/', views.article_detail),
]"""

try_django/mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

try_django/mysite/news/models.py
import datetime
from django.db import models
from django.utils import timezone


class Reporter(models.Model):
    full_name = models.CharField(max_length=70)

    def __str__(self):
        return self.full_name

class Article(models.Model):
    pub_date = models.DateField()
    headline = models.CharField(max_length=200)
    content = models.TextField()
    reporter = models.ForeignKey(Reporter, on_delete=models.CASCADE)

    def __str__(self):
        return self.headline

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

try_django/mysite/polls/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

try_django/mysite/news/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Article

class ArticleView(generic.ListView):
    model = Article
    template_name = 'news/article_archive.html'

    def get_queryset(self):
        return Article.objects.filter(pub_date__lte=timezone.now())

def year_archive(request, year):
    a_list = Article.objects.filter(pub_date__year=year)
    context = {'year': year, 'article_list': a_list}
    return render(request, 'news/year_archive.html', context)

"""class YearView(generic.DetailView):
    model = Article
    template_name = 'news/year_archive.html'"""

def month_archive(request, year, month):
    a_list = Article.objects.filter(pub_date__year=year, pub_date__month=month)
    context = {'year': year, 'month': month, 'article_list': a_list}
    return render(request, 'news/month_archive.html', context) 

class DetailView(generic.DetailView):
    model = Article
    template_name = 'news/aritcle_detail.html'

"""def article_archive(request):
    a_list = Article.objects.order_by('-pub_date')
    context = {'article_list' : a_list}
    return render(request, 'news/article_archive.html',context)"""


"""class MonthView(generic.ListView):
    model = Article
    template_name = 'news/month_archive.html'"""

#def article_detail(request, year, month, pk):
    #a_list = Article.objects.filter(pub_date__year=year, pub_date__month=month, pk = pk)
    #context = {'year': year, 'month': month, 'article_list': a_list}
    #return render(request, 'news/aritcle_detail.html', context) 

try_django/mysite/polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Question

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {'question': question, 'error_message': "You didn't select a choice.",})
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

try_django/mysite/news/templates/base.html
{% load static %}
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <img src="{% static "logo.png" %}" alt="Logo">
    {% block content %}{% endblock %}
</body>
</html>

try_django/mysite/news/templates/news/aritcle_detail.html
{% extends "base.html" %}

{% block title %}Articles f0r {{ article.pub_date|date:"Y" }}.{{ article.pub_date|date:"m" }}, No. {{ article.id }}{% endblock %}

{% block content %}
<h1>Articles for {{ article.pub_date|date:"Y" }} . {{ article.pub_date|date:"m" }}, No. {{article.id}}</h1>
    <p>{{ article.headline }}</p>
    <hr>
    <p>{{ article.content }}</p>
    <p>By {{ article.reporter.full_name }}</p>
    <p>Published {{ article.pub_date|date:"F j, Y" }}</p>
    <p>Id {{article.id}}</p>
{% endblock %}

try_django/mysite/news/templates/news/article_archive.html
{% extends "base.html" %}

{% block title %}A list of Articles {% endblock %}

{% block content %}
<h1>A list of Articles</h1>

<ul>
{% for article in article_list %}
    <a href="{% url 'news:year' article.pub_date|date:"Y" %}">{{ article.pub_date|date:"Y" }}</a>
    <p>{{ article.headline }}</p></li>
{% endfor %}
</ul>

{% endblock %}

try_django/mysite/news/templates/news/month_archive.html
{% extends "base.html" %}

{% block title %}Articles for {{ year }}.{{ month }}{% endblock %}

{% block content %}
<h1>Articles for {{ year }} . {{ month }}</h1>

{% for article in article_list %}
    <p>{{ article.headline }}</p>
    <p>By {{ article.reporter.full_name }}</p>
    <p>Published {{ article.pub_date|date:"F j, Y" }}</p>
    <br>
{% endfor %}
{% endblock %}

try_django/mysite/news/templates/news/year_archive.html
{% extends "base.html" %}

{% block title %}Articles for {{ year }}{% endblock %}

{% block content %}
<h1>Articles for {{ year }}</h1>

{% for article in article_list %}
    <p>{{ article.headline }}</p>
    <p>By {{ article.reporter.full_name }}</p>
    <p>Published {{ article.pub_date|date:"F j, Y" }}</p>
    <br>
    
{% endfor %}
{% endblock %}

try_django/mysite/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

try_django/mysite/polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

try_django/mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>